Convert role into collection
Worteks/ansible-lemonldapng pull request #9
Opened 2022-02-15 13:35 UTC by l00ptr

We move the role files under the roles folder and we also adapt the
molecule default scenario and the documentation. It's the first step before adding some plugins to manipulate the config through the LemonLDAP::NG API.

2022-02-17 17:33 UTC, maxbes requested changes

2022-02-17 17:33 UTC, maxbes commented on galaxy.yml
> +readme: README.md
Please update the README to reflect the new role path in the example

2023-12-27 22:37 UTC, l00ptr commented
Any feedback for this (long standing) MR ?

2024-01-02 16:35 UTC, maxbes approved these changes

2024-01-02 16:36 UTC, maxbes commented
@coudot looks good to me

2024-01-12 17:02 UTC, l00ptr commented
I will have some free time to work on some improvement / maintenance on this collection the 2 next weeks. I will create a new branch starting from the unmerged one.

2024-01-15 06:59 UTC, merged

2024-01-15 07:00 UTC, coudot commented
Hello @l00ptr 

following review from @maxbes I merged this PR. You can start a new one from master branch if you want.

Thanks again for your contribution.

2024-01-15 11:53 UTC, l00ptr commented
@coudot great thx!